
all: deepcopy_pe deepcopy_plat dico exception inter log matposi msg pe roc_bots_one roc_bots_two roc_theorie

deepcopy_pe:
	make -C ../test_deepcopy_pe

deep_plat:
	make -C ../test_deepcopy_plat

dico:
	make -C ../test_dico
	
exception:
	make -C ../test_exception

inter:
	make -C ../test_inter

log:
	make -C ../test_log

matposi:
	make -C ../test_matposi

msg:
	make -C ../test_msg

pe:
	make -C ../test_pe

roc_bots_one:
	make -C ../test_roc_bots_one

roc_bots_two:
	make -C ../test_roc_bots_two

roc_theorie:
	make -C ../test_roc_theorie
	

.PHONY: deepcopy_pe deepcopy_plat dico exception inter log matposi msg pe roc_bots_one roc_bots_two roc_theorie all 
