
all: deepcopy_pe deepcopy_plat dico e_et_m_bots exception interpret log matposi mise_en_echec_et_mat msg pat_bots pe roc_bots_one roc_bots_real roc_bots_two roc_theorie

deepcopy_pe:
	make -C ../test_deepcopy_pe

deep_plat:
	make -C ../test_deepcopy_plat

e_et_m_bots:
	make -C ../test_dico
	
dico:
	make -C ../test_e_et_m_bots

exception:
	make -C ../test_exception

interpret:
	make -C ../test_interpret

log:
	make -C ../test_log

matposi:
	make -C ../test_matposi
	
mise_en_echec_et_mat:
	make -C ../test_mise_en_echec_et_mat

msg:
	make -C ../test_msg
	
pat_bots:
	make -C ../test_pat_bots

pe:
	make -C ../test_pe

roc_bots_one:
	make -C ../test_roc_bots_one

roc_bots_real:
	make -C ../test_roc_bots_real

roc_bots_two:
	make -C ../test_roc_bots_two

roc_theorie:
	make -C ../test_roc_theorie
	

.PHONY: deepcopy_pe deepcopy_plat dico e_et_m_bots exception interpret log matposi mise_en_echec_et_mat msg pat_bots pe roc_bots_one roc_bots_real roc_bots_two roc_theorie all 
